parameters:
#    innovit_user.example.class: Innovit\UserBundle\Example

services:
#    innovit_user.example:
#        class: %innovit_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
