parameters:
#    innovit_profil.example.class: Innovit\ProfilBundle\Example

services:
#    innovit_profil.example:
#        class: %innovit_profil.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
